name: Backpacks
version: 1.0.0
description: Simple plugin implementing virtual backpacks
author: macca_ferri
website: https://emilianomaccaferri.com
main: com.emilianomaccaferri.backpacks.Backpacks

commands:
  backpack:
    description: Do that
    usage: /backpack
